// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'my_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC44NeJH8ZAC4_RzIOrZrR8TdwoWaFrSCk',
    appId: '1:966491289962:web:73eb169de0c0e26cad0d13',
    messagingSenderId: '966491289962',
    projectId: 'logstock-281a7',
    authDomain: 'logstock-281a7.firebaseapp.com',
    storageBucket: 'logstock-281a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKbn2nWti3F5DZ3ptAppt71hL81c47phU',
    appId: '1:966491289962:android:e685b3c8ab9d8fcaad0d13',
    messagingSenderId: '966491289962',
    projectId: 'logstock-281a7',
    storageBucket: 'logstock-281a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANgY20iHu6rgUMc3se3K7qV0koFqEfg8U',
    appId: '1:966491289962:ios:d7cf0228133450b8ad0d13',
    messagingSenderId: '966491289962',
    projectId: 'logstock-281a7',
    storageBucket: 'logstock-281a7.appspot.com',
    iosClientId: '966491289962-jff3nphva7cvs26dieqd44hq43u94qqf.apps.googleusercontent.com',
    iosBundleId: 'br.com.rrocha22.logstock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANgY20iHu6rgUMc3se3K7qV0koFqEfg8U',
    appId: '1:966491289962:ios:d7cf0228133450b8ad0d13',
    messagingSenderId: '966491289962',
    projectId: 'logstock-281a7',
    storageBucket: 'logstock-281a7.appspot.com',
    iosClientId: '966491289962-jff3nphva7cvs26dieqd44hq43u94qqf.apps.googleusercontent.com',
    iosBundleId: 'br.com.rrocha22.logstock',
  );
}
